import Head from 'next/head';
import Header from './header';

export default function Layout(props) {
  return (
    <div>
      <Head>
        <title>Job Search Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="px-8">
        <main className="min-h-screen py-8 flex flex-col justify-center items-center">
          {props.children}
        </main>
        <footer className="flex flex-1 py-8 border-t border-zinc-700 justify-center items-center">
          <div>
            Footer
          </div>
        </footer>
      </div>
    </div>
  );
};