-- Interviews table
create table interviews (
  id bigint generated by default as identity primary key,
  job_id bigint references jobs(id) not null,
  interview_type text,
  interview_at date not null,
  responded_at date,
  response text
);

alter table interviews enable row level security;

create policy "Individuals can create interviews." on interviews for
  insert with check (
    exists (
      select 1
      from jobs
      where jobs.id = interviews.job_id
    )
  );

create policy "Individuals can view their own interviews." on interviews for
  select using (
    exists (
      select 1
      from jobs
      where jobs.id = interviews.job_id
    )
  );

create policy "Individuals can update their own interviews." on interviews for
  update using (
    exists (
      select 1
      from jobs
      where jobs.id = interviews.job_id
    )
  );

create policy "Individuals can delect their own interviews." on interviews for
  delete using (
    exists (
      select 1
      from jobs
      where jobs.id = interviews.job_id
    )
  );