-- Jobs table
create table jobs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  company text not null,
  job_title text not null,
  years_experience int,
  posted_at date,
  site_posted text,
  applied_at date not null,
  responded_at date,
  response text
);

alter table jobs enable row level security;

create policy "Individuals can create jobs." on jobs for
  insert with check (auth.uid() = user_id);

create policy "Individuals can view their own jobs." on jobs for
  select using (auth.uid() = user_id);

create policy "Individuals can update their own jobs." on jobs for
  update using (auth.uid() = user_id);

create policy "Individuals can delect their own jobs." on jobs for
  delete using (auth.uid() = user_id);