import { useState, useEffect } from 'react';
import '../styles/globals.css';
import Head from 'next/head';
import Header from '../components/Header';
import { supabase } from './api/supabaseClient';
import { ResponseContext } from '../context/contexts';

export default function MyApp({ Component, pageProps }) {
  const [authState, setAuthState] = useState("not-auth");
  const [responseContext, setResponseContext] = useState('');

  useEffect(() => {
    const { data: authListener } = supabase.auth.onAuthStateChange((event, session) => {
      handleAuthChange(event, session);
      if (event === "SIGNED_IN") {
        setAuthState("auth");
      }
      if (event === "SIGNED_OUT") {
        setAuthState("not-auth");
      }
    });
    checkUser();
    return () => {
      authListener.unsubscribe();
    };
  }, []);

  async function checkUser() {
    const user = supabase.auth.user();
    if (user) {
      setAuthState("auth");
    }
  }

  async function handleAuthChange(event, session) {
    await fetch("/api/auth", {
      method: "POST",
      headers: new Headers({ "Content-Type": "application/json" }),
      credentials: "same-origin",
      body: JSON.stringify({ event, session })
    });
  }

  const getLayout = Component.getLayout || ((page) => page);

  return (
    <ResponseContext.Provider value={[responseContext, setResponseContext]}>
      <div>
        <Head>
          <title>Job Search Web App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header authState={authState} />
        {getLayout(<Component {...pageProps} />)}
      </div>
    </ResponseContext.Provider>
  );
};